import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { CheckCircle, Clock, Star } from "lucide-react";
const TEACHER_PERFORMANCE = [
    { metric: 'Attendance', value: 98 },
    { metric: 'Syllabus', value: 85 },
    { metric: 'Student Avg', value: 72 },
    { metric: 'Parent Rating', value: 90 },
];
export const StaffProfile = () => {
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-7xl mx-auto space-y-8", children: [_jsxs("div", { className: "flex gap-6 items-center", children: [_jsx("div", { className: "w-24 h-24 rounded-full bg-blue-600 flex items-center justify-center text-3xl font-bold text-white", children: "JD" }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white", children: "Mr. John Doe" }), _jsx("p", { className: "text-slate-400", children: "Senior Math Teacher \u2022 Staff ID: S-101" })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [_jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-slate-400 text-sm", children: "Classes Taught" }), _jsx("p", { className: "text-3xl font-bold text-white mt-2", children: "4" }), _jsxs("div", { className: "flex items-center gap-1 text-slate-500 text-sm mt-2", children: [_jsx(Clock, { size: 16 }), " 24 Hours/Week"] })] }), _jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-slate-400 text-sm", children: "Task Completion" }), _jsx("p", { className: "text-3xl font-bold text-white mt-2", children: "95%" }), _jsxs("div", { className: "flex items-center gap-1 text-green-500 text-sm mt-2", children: [_jsx(CheckCircle, { size: 16 }), " On Track"] })] }), _jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-slate-400 text-sm", children: "Performance Score" }), _jsx("p", { className: "text-3xl font-bold text-white mt-2", children: "4.8/5" }), _jsxs("div", { className: "flex items-center gap-1 text-yellow-500 text-sm mt-2", children: [_jsx(Star, { size: 16 }), " Star Teacher"] })] })] }), _jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-white mb-6", children: "Teacher Performance Metrics (ROI)" }), _jsx("div", { className: "h-[300px] w-full", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(BarChart, { data: TEACHER_PERFORMANCE, layout: "vertical", children: [_jsx(CartesianGrid, { strokeDasharray: "3 3", stroke: "#1e293b" }), _jsx(XAxis, { type: "number", domain: [0, 100], stroke: "#64748b" }), _jsx(YAxis, { dataKey: "metric", type: "category", stroke: "#64748b", width: 100 }), _jsx(Tooltip, { cursor: { fill: '#1e293b' }, contentStyle: { backgroundColor: '#0f172a', border: '1px solid #1e293b' } }), _jsx(Bar, { dataKey: "value", fill: "#8B5CF6", radius: [0, 4, 4, 0], barSize: 20 })] }) }) })] })] }));
};
