import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, ResponsiveContainer } from "recharts";
import { Smile, DollarSign } from "lucide-react";
const WELLBEING_DATA = [
    { subject: 'Academic', A: 120, fullMark: 150 },
    { subject: 'Social', A: 98, fullMark: 150 },
    { subject: 'Health', A: 86, fullMark: 150 },
    { subject: 'Discipline', A: 99, fullMark: 150 },
    { subject: 'Sports', A: 85, fullMark: 150 },
    { subject: 'Art', A: 65, fullMark: 150 },
];
export const StudentProfile = () => {
    // Ideally receives student ID from params
    return (_jsxs("div", { className: "p-6 md:p-8 max-w-7xl mx-auto space-y-8", children: [_jsxs("div", { className: "flex gap-6 items-center", children: [_jsx("img", { src: "https://api.dicebear.com/7.x/avataaars/svg?seed=Felix", alt: "Student", className: "w-24 h-24 rounded-full border-4 border-slate-800 bg-slate-800" }), _jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-white", children: "Felix K." }), _jsx("p", { className: "text-slate-400", children: "Class 5A \u2022 ID: 2024001" })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-6", children: [_jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-white mb-6", children: "360\u00B0 Student Pulse" }), _jsx("div", { className: "h-[300px] w-full", children: _jsx(ResponsiveContainer, { width: "100%", height: "100%", children: _jsxs(RadarChart, { cx: "50%", cy: "50%", outerRadius: "80%", data: WELLBEING_DATA, children: [_jsx(PolarGrid, { stroke: "#1e293b" }), _jsx(PolarAngleAxis, { dataKey: "subject", stroke: "#94a3b8" }), _jsx(PolarRadiusAxis, { angle: 30, domain: [0, 150], stroke: "#1e293b" }), _jsx(Radar, { name: "Felix", dataKey: "A", stroke: "#8884d8", fill: "#8884d8", fillOpacity: 0.6 })] }) }) })] }), _jsxs("div", { className: "bg-slate-900 border border-slate-800 rounded-2xl p-6", children: [_jsx("h3", { className: "text-lg font-semibold text-white mb-4", children: "Wellbeing & Survey Analysis" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "p-4 bg-slate-950 rounded-xl border border-slate-800", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(Smile, { className: "text-green-500", size: 20 }), _jsx("h4", { className: "font-medium text-white", children: "Positive Sentiment" })] }), _jsx("p", { className: "text-slate-400 text-sm", children: "Analysis of recent chatbot interactions shows high engagement in Sports and Science. Felix seems happy but mentioned \"Math is getting harder\"." })] }), _jsxs("div", { className: "p-4 bg-slate-950 rounded-xl border border-slate-800", children: [_jsxs("div", { className: "flex items-center gap-2 mb-2", children: [_jsx(DollarSign, { className: "text-yellow-500", size: 20 }), _jsx("h4", { className: "font-medium text-white", children: "Fee Status" })] }), _jsxs("p", { className: "text-slate-400 text-sm", children: ["Balance: ", _jsx("strong", { children: "50,000 UGX" }), ". Next installment due in 14 days. Parent has been notified via WhatsApp."] })] })] })] })] })] }));
};
